# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: social_network.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14social_network.proto\"9\n\x04User\x12\r\n\x05login\x18\x01 \x01(\t\x12\x15\n\x08password\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_password\"7\n\x05Phone\x12\x1e\n\nphone_type\x18\x01 \x01(\x0e\x32\n.PhoneType\x12\x0e\n\x06number\x18\x02 \x01(\x04\"\xb9\x01\n\x0bUserProfile\x12\r\n\x05login\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\r\x12\x0e\n\x06height\x18\x05 \x01(\x01\x12\x17\n\x06gender\x18\x06 \x01(\x0e\x32\x07.Gender\x12\x16\n\x06phones\x18\n \x03(\x0b\x32\x06.Phone\x12\x17\n\navatar_url\x18\x64 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_avatar_url\"J\n\x07Message\x12\x15\n\x06sender\x18\x01 \x01(\x0b\x32\x05.User\x12\x17\n\x08receiver\x18\x02 \x01(\x0b\x32\x05.User\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x07\n\x05\x45mpty*\x1e\n\x06Gender\x12\x08\n\x04Male\x10\x00\x12\n\n\x06\x46\x65male\x10\x01*+\n\tPhoneType\x12\x08\n\x04Home\x10\x00\x12\x08\n\x04Work\x10\x01\x12\n\n\x06Mobile\x10\x02\x32\x37\n\x0eProfileManager\x12%\n\x0eGetUserProfile\x12\x05.User\x1a\x0c.UserProfile2T\n\x0b\x43hatService\x12\x1f\n\x0bSendMessage\x12\x08.Message\x1a\x06.Empty\x12$\n\x0fReceiveMessages\x12\x05.User\x1a\x08.Message0\x01\x42\x17Z\x15generated/chat_serverb\x06proto3')

_GENDER = DESCRIPTOR.enum_types_by_name['Gender']
Gender = enum_type_wrapper.EnumTypeWrapper(_GENDER)
_PHONETYPE = DESCRIPTOR.enum_types_by_name['PhoneType']
PhoneType = enum_type_wrapper.EnumTypeWrapper(_PHONETYPE)
Male = 0
Female = 1
Home = 0
Work = 1
Mobile = 2


_USER = DESCRIPTOR.message_types_by_name['User']
_PHONE = DESCRIPTOR.message_types_by_name['Phone']
_USERPROFILE = DESCRIPTOR.message_types_by_name['UserProfile']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'social_network_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

Phone = _reflection.GeneratedProtocolMessageType('Phone', (_message.Message,), {
  'DESCRIPTOR' : _PHONE,
  '__module__' : 'social_network_pb2'
  # @@protoc_insertion_point(class_scope:Phone)
  })
_sym_db.RegisterMessage(Phone)

UserProfile = _reflection.GeneratedProtocolMessageType('UserProfile', (_message.Message,), {
  'DESCRIPTOR' : _USERPROFILE,
  '__module__' : 'social_network_pb2'
  # @@protoc_insertion_point(class_scope:UserProfile)
  })
_sym_db.RegisterMessage(UserProfile)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'social_network_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'social_network_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_PROFILEMANAGER = DESCRIPTOR.services_by_name['ProfileManager']
_CHATSERVICE = DESCRIPTOR.services_by_name['ChatService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025generated/chat_server'
  _GENDER._serialized_start=413
  _GENDER._serialized_end=443
  _PHONETYPE._serialized_start=445
  _PHONETYPE._serialized_end=488
  _USER._serialized_start=24
  _USER._serialized_end=81
  _PHONE._serialized_start=83
  _PHONE._serialized_end=138
  _USERPROFILE._serialized_start=141
  _USERPROFILE._serialized_end=326
  _MESSAGE._serialized_start=328
  _MESSAGE._serialized_end=402
  _EMPTY._serialized_start=404
  _EMPTY._serialized_end=411
  _PROFILEMANAGER._serialized_start=490
  _PROFILEMANAGER._serialized_end=545
  _CHATSERVICE._serialized_start=547
  _CHATSERVICE._serialized_end=631
# @@protoc_insertion_point(module_scope)
